name: "Twasi Utilities"
main: Plugin
author: Twasi Team
description: Basic Twasi Utilities Plugin.
helpText: "Basic functionality for Twasi!"
version: 1.0

messageHandler: false

commands:
  - check
  - wiki
  - title
  - status
  - game
  - uptime

permissions:
  - twasi.utilities.mod.title
  - twasi.utilities.mod.game