name: "Utilities"
main: net.twasiplugin.utilities.Plugin
author: Twasi Team
description: Basic Twasi Utilities Plugin.
helpText: "Basic functionality for Twasi!"
version: 1.0

messageHandler: false

commands:
  - check
  - wiki
  - title
  - status
  - game
  - uptime
  - hosts

permissions:
  - twasi.utilities.mod.title
  - twasi.utilities.mod.game

api: |
  type Utilities {
    twitchAPI: TwitchAPI
  }

  type TwitchAPI {
    retrieve: TwitchAPIRequest,
    update: TwitchAPIUpdate
  }

  type TwitchAPIUpdate {
    title(newTitle: String): Boolean,
    game(newGame: String): Boolean,
    channel(newTitle: String, newGame: String): Boolean
  }

  type TwitchAPIRequest {
    title: String,
    game: String,
    followers: Int
  }