name: "Twasi Utilities"
main: de.merlinw.twasi.utilities.Plugin
author: Twasi Team
description: Basic Twasi Utilities Plugin.
helpText: "Basic functionality for Twasi!"
version: 1.0

messageHandler: false

commands:
  - check
  - wiki
  - title
  - game

permissions:
  - twasi.utilities.mod.title
  - twasi.utilities.mod.game